---
- name: Installing CoovaChilli for RadiusDesk (Ubuntu)
  apt:
    name="coova-chilli=1.3.3-rd*"
    state=present

- name: Enabling CoovaChilli Daemon for RadiusDesk (Ubuntu)
  lineinfile:
    dest="{{ coovachilli_default_conf }}"
    line="START_CHILLI=1"
    regexp="^START_CHILLI"
    state=present

- name: Disabling CoovaChilli Default Splash Page for RadiusDesk (Ubuntu)
  lineinfile:
    dest: "{{ coovachilli_conf_dir }}/defaults"
    line: "#HS_UAMHOMEPAGE=http://\\$HS_UAMLISTEN:\\$HS_UAMPORT/www/coova.html"
    regexp: "^HS_UAMHOMEPAGE"
    state: present

- name: Disabling CoovaChilli Default HS_UAMALLOW for RadiusDesk (Ubuntu)
  lineinfile:
    dest: "{{ coovachilli_conf_dir }}/defaults"
    line: "#HS_UAMALLOW=www.coova.org"
    regexp: "^HS_UAMALLOW"
    state: present

- name: Configuring CoovaChilli for RadiusDesk (Ubuntu)
  template:
    dest="{{ coovachilli_conf_dir }}/config"
    group={{ coovachilii_group }}
    src="coova/chilli.config.j2"

- name: Configuring UAM Service for RadiusDesk Login (Ubuntu)
  template:
    dest="{{ nginx_webroot }}/rd_login/services/uam.php"
    owner={{ web_user }}
    group={{ web_group }}
    src="uam.php.j2"

- name: Configuring CoovaChilli Start Up IPTables rules (Ubuntu)
  template:
    dest="/etc/chilli/ipup.sh"
    mode=777
    src="coova/ipup.sh.j2"

- name: Configuring CoovaChilli Shutdown IPTables rules (Ubuntu)
  template:
    dest="/etc/chilli/ipdown.sh"
    mode=777
    src="coova/ipdown.sh.j2"

- name: Installing CoovaChilli Start Up Service (Ubuntu)
  template:
    dest="/etc/init.d/chilli"
    mode=755
    src="coova/chilli.init.{{ ansible_os_family }}.j2"

- name: Ensuring CoovaChilli is Properly Configured (Ubuntu)
  shell: update-rc.d chilli defaults
  notify:
    - Restart MySQL
    - Restart Freeradius
    - Restart Coovachilli