---
- name: Ensuring Apache is not installed (Ubuntu)
  apt:
    name={{ apache_pkg_name }}
    state=absent

- name: Installing Nginx (Ubuntu)
  apt:
    name={{ nginx_pkg_name }}
    state=installed
    update_cache=yes

- name: Installing RadiusDesk packages (Ubuntu)
  apt:
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: "{{ rd_pkgs }}"
  notify:
    - Start Nginx
    - Start PHP-FPM

- name: Configuring PHP-FPM to use UNIX sockets (Ubuntu)
  template:
    src="nginx/php_fpm.www.conf.j2"
    dest={{ php_fpm_config }}

- name: Configuring Nginx to use UNIX sockets (Ubuntu)
  template:
    src="nginx/nginx.default.conf.j2"
    dest={{ nginx_default_config }}

- name: Configuring Nginx for RadiusDesk Web Compression (Ubuntu)
  template:
    src="nginx/nginx.conf.j2"
    dest={{ nginx_config }}
  notify:
    - Restart Nginx
    - Restart PHP-FPM

- name: Downloading CakePHP Source from Github (Ubuntu)
  git: 
    dest={{ temp_src_dir }}/cake2
    repo={{ cakephp_git_repo }}
    update=no
    version=2.7.9

- name: Copying CakePHP Source to Webroot (Ubuntu)
  shell: cp -a {{ temp_src_dir | quote }}/cake2 {{ nginx_webroot | quote }}/cake2

- name: Downloading RadiusDesk CakePHP Source from Subversion (Ubuntu)
  subversion:
    repo={{ rd_cake_svn_repo }}
    dest={{ temp_src_dir }}/rd_cake
    revision={{ rd_svn_revision }}

- name: Copying RadiusDesk CakePHP App Source to Webroot (Ubuntu)
  shell: cp -a {{ temp_src_dir | quote }}/rd_cake {{ nginx_webroot | quote }}/cake2/

- name: Downloading RadiusDesk Viewer Source from Subversion (Ubuntu)
  subversion:
    repo={{ rd_svn_repo }}
    dest={{ temp_src_dir }}/rd
    revision={{ rd_svn_revision }}

- name: Copying RadiusDesk Viewer Source to Webroot (Ubuntu)
  shell: cp -a {{ temp_src_dir | quote }}/rd {{ nginx_webroot | quote }}/

- name: Downloading RadiusDesk Login Source from Subversion (Ubuntu)
  subversion:
    repo={{ rd_login_svn_repo }}
    dest={{ temp_src_dir }}/rd_login
    revision={{ rd_svn_revision }}

- name: Copying RadiusDesk Login Source webroot (Ubuntu)
  shell: cp -a {{ temp_src_dir | quote }}/rd_login {{ nginx_webroot | quote }}/

- name: Configuring UAM Service for RadiusDesk Login (Ubuntu)
  template:
    dest="{{ nginx_webroot }}/rd_login/services/uam.php"
    src="uam.php.j2"

- name: Checking if we already downloaded ExtJS 6 sources (Ubuntu)
  stat:
    path="{{ temp_src_dir }}/ext-6-sencha_cmd.tar.gz"
  register: extjs_src

- name: Downloading ExtJS 6 sources from Subversion (Ubuntu)
  get_url:
    url={{ extjs_src_url }}
    dest="{{ temp_src_dir }}/ext-6-sencha_cmd.tar.gz"
  when: "extjs_src.stat.exists == False or extjs_src.stat.md5 != '{{ extjs_src_md5_sum }}'"

- name: Extracting ExtJS 6 archive for RadiusDesk Viewer (Ubuntu)
  unarchive:
    src="{{ temp_src_dir }}/ext-6-sencha_cmd.tar.gz"
    dest={{ nginx_webroot }}/rd/
    owner={{ web_user }}
    group={{ web_group }}
    mode=0664
    copy=no
  # when: "extjs_src.stat.exists == True"

- name: Correcting Webroot ownership and permissions (Ubuntu)
  file:
    path={{ nginx_webroot }}
    owner={{ web_user }}
    group={{ web_group }}
    mode=0775
    state=directory
    recurse=yes

- name: Fix PHP Default Timezone
  lineinfile: 
    dest="{{ php_config_file }}"
    line='date.timezone = {{ php_timezone }}'
    regexp='^;date.timezone'

- name: Ensuring Nginx is Started (Ubuntu)
  service:
    name={{ nginx_service_name }}
    state=started

- name: Ensuring PHP-FPM is Started (Ubuntu)
  service:
    name={{ php_fpm_service_name }}
    state=started

- name: Configuring RadiusDesk Cron Jobs (Ubuntu)
  template:
    src="cron/cron.j2"
    dest="/etc/cron.d/rd"

- name: Ensuring MySQL is Started (Ubuntu)
  service:
    name={{ mysql_service_name }}
    state=started

- name: Ensuring MySQL Root password has been set (Ubuntu)
  stat:
    path={{ mysql_my_cnf }}
  register: mysql_conf

- name: Changing MySQL Root password (Ubuntu)
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
    state=present
  with_items: "{{ mysql_db_hosts }}"
  notify:
    - Restart MySQL
  when: mysql_conf.stat.exists == False

- name: Adding .my.cnf for MySQL root Password Idempotency (Ubuntu)
  template:
    src="my.cnf.j2"
    dest={{ mysql_my_cnf }}
  when: mysql_conf.stat.exists == False

- name: Remove Anonymous MySQL Users (Ubuntu)
  mysql_user:
    name=''
    host={{ item }}
    state=absent
    login_user=root
    login_password={{ mysql_root_password }}
  with_items: "{{ mysql_db_hosts }}"

- name: Creating RadiusDesk Database (Ubuntu)
  mysql_db:
    name={{ rd_db_name }}
    state=present
    login_user=root
    login_password={{ mysql_root_password }}

- name: Creating RadiusDesk Database User (Ubuntu)
  mysql_user:
    "name={{ rd_db_user }}
    password={{ rd_db_password }}
    priv={{ rd_db_name }}.*:ALL
    state=present
    login_user=root
    login_password={{ mysql_root_password }}
    host={{ item }}"
  with_items: "{{ mysql_db_hosts }}"

- name: Importing RadiusDesk Database (Ubuntu)
  mysql_db:
    state=import
    name={{ rd_db_name }}
    target={{ nginx_webroot }}/cake2/rd_cake/Setup/Db/rd.sql
    login_user=root
    login_password={{ mysql_root_password }}
