---
# Apache (Debian/Ubuntu)
apache_pkg_name: apache2

# RadiusDesk Packages (Debian/Ubuntu)
rd_pkgs:
 - language-pack-en-base
 - language-pack-af
 - language-pack-fa
 - php5-fpm
 - mysql-server
 - mysql-client
 - php5-mysql
 - python-mysqldb
 - php5-xcache
 - php5-cli
 - php5-gd
 - php5-curl
 - subversion
 - git
 - unzip
 - tar

# Nginx (Debian/Ubuntu)
nginx_pkg_name: nginx
nginx_service_name: nginx
nginx_webroot: "/usr/share/nginx/html"
nginx_config: "/etc/nginx/nginx.conf"
nginx_default_config: "/etc/nginx/sites-enabled/default"
nginx_worker_processes: 4
nginx_user: www-data

# PHP-FPM (Debian/Ubuntu)
php_fpm_service_name: php5-fpm
php_fpm_config: "/etc/php5/fpm/pool.d/www.conf"
php_fpm_socket: "/var/run/php5-fpm.sock"
php_session_save_path: "/tmp"
php_config_file: "/etc/php5/cli/php.ini"
php_timezone: "Africa/Lagos"

# Web server (Debian/Ubuntu)
web_user: www-data
web_group: www-data

# Temporary Download Directory
temp_src_dir: "/tmp/rd_sources"

# Radiusdesk Sources Repo Paths (Debian/Ubuntu)
cakephp_git_repo: "https://github.com/cakephp/cakephp.git"
rd_svn_repo: "http://svn.code.sf.net/p/radiusdesk/code/trunk/rd"
rd_cake_svn_repo: "http://svn.code.sf.net/p/radiusdesk/code/trunk/rd_cake"
rd_login_svn_repo: "http://svn.code.sf.net/p/radiusdesk/code/trunk/rd_login"
extjs_src_url: "https://sourceforge.net/p/radiusdesk/code/HEAD/tree/extjs/ext-6-sencha_cmd.tar.gz?format=raw"
extjs_src_md5_sum: "e829741694be90a27d7f0c6a24dbfc8b"
rd_svn_revision: 1633

# Freeradius Packages (Debian/Ubuntu)
freeradius_pkgs:
 - "freeradius=2.2.9-rd*"
 - "freeradius-utils=2.2.9-rd*"
 - "freeradius-mysql=2.2.9-rd*"
 - "freeradius-ldap=2.2.9-rd*"
 - "freeradius-krb5=2.2.9-rd*"
 - "freeradius-common=2.2.9-rd*"
 - libnet-telnet-perl

# Freeradius (Debian/Ubuntu)
freeradius_conf_dir: "/etc/freeradius"
freeradius_prefix_path: ""
freeradius_sbin_dir: "/usr/sbin"
freeradius_bin_dir: "/usr/bin"
freeradius_shared_dir: "/usr/share/freeradius"
freeradius_service_name: freeradius
freeradius_user: freerad
freeradius_group: freerad
freeradius_log_dir: "/var/log/freeradius"
allow_vulnerable_openssl: yes

# Radiusdesk Database (Debian/Ubuntu)
rd_db_user: rd
rd_db_password: rd
rd_db_name: rd

# MySQL (Debian/Ubuntu)
mysql_old_root_password: ""
mysql_root_password: root
mysql_service_name: mysql
mysql_db_hosts:
 - 127.0.0.1
 - localhost
mysql_my_cnf: "~/.my.cnf"

# Nodejs Packages (Debian/Ubuntu)
nodejs_pkgs:
 - python-software-properties
 - software-properties-common
 - g++
 - make
 - nodejs

# Nodejs Modules (Debian/Ubuntu)
nodejs_npm_modules:
 - tail
 - connect
 - mysql
 - forever

nodejs_socketio_service_name: "nodejs-socket-io"

# PPTPD
enable_pptpd_support: yes
pptpd_service_name: pptpd
pptpd_local_ip_network: "10.20.30"
pptpd_client_dir: "/etc/ppp"

# CoovaChilli
enable_coovachilli_support: no
coovachilli_service_name: chilli
coovachilli_conf_dir: "/etc/chilli"
coovachilli_default_conf: "/etc/default/chilli"
coovachilii_lan_if: "eth2"
coovachilii_wan_if: "eth1"
coovachilii_server_ip: "192.168.2.1"
coovachilii_network_addr: "192.168.2.0"
coovachilii_network_subnet: "255.255.255.0"
coovachilii_uam_port: 3990
coovachilii_uam_secret: "greatsecret"
coovachilii_radius_server1: "localhost"
coovachilii_radius_server2: "localhost"
coovachilii_dns_server1: "208.67.222.222"
coovachilii_dns_server2: "208.67.220.220"
coovachilii_user: "chilli"
coovachilii_group: "chilli"

# MAO Repository
mao_apt_ppa_repo: "ppa:muffycompoqm/rd-installer"
mao_apt_repo_key: "http://apt.maomuffy.com/ubuntu/apt_keys/rd_installer_mao.asc"

# NodeJS Repository
node_apt_repo_key: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
